### ISSUE TITLE
1201 alarm. No go for flight / infinite loop

### ISSUE THREAD

**Issue by gbm** [kislyuk/watchtower#140] opened 2021-02-24 15:04 UTC
@kislyuk I didn't mean any disrespect with the previous issue - I think this is a great library and AWS should hire you. 

But I've hit in infinite loop in 1.0.6 and for me it's a no go for flight (do not use in production)

**Comment by kislyuk** [comment] 2021-02-24 16:32
@gbm thanks for your kind words.

Do you have any pointers on how to reproduce your issue?

**Comment by gbm** [comment] 2021-02-24 16:59
I will check what I am allowed to share. 
Again just to reiterate I am personally full of admiration for you maintaining this largely on your own. 
And for me you are obvious acquihire for AWS.

**Comment by gbm** [comment] 2021-02-25 03:53
@kislyuk 
What I can share today is that the loop seemed to end here
https://github.com/kislyuk/watchtower/blob/develop/watchtower/__init__.py#L276
I don't have root cause and don't expect to immediately.

**Comment by gbm** [comment] 2021-02-25 11:42
The infinite loop has just "gone away". No code changes made. May have been some network changes - unclear. It manifested for about ~ 16 hours ballpark. Appeared. Went away.

**Comment by gbm** [comment] 2021-03-03 18:01
@kislyuk unable to duplicate to far. Machine untouched. Will update.

**Comment by gbm** [comment] 2021-03-05 16:21
@kislyuk only had time to look at this very briefly so thought I would just brain-dump some thoughts. 

So far with the little time I have had I haven't been able to duplicate the infinite loop. 

Possibly I won't be able to easily and so the only resolution is via code inspection / mocking. 

There have been no code changes - there may have been network changes either internally or at AWS (change in response)

This would indicate that it was the send functionality in the loop above that somehow failed in an edge case and caused the infinite loop. 

I share this in the hope it will help others although I will continue to look at this as time allows.

**Comment by gbm** [comment] 2021-03-11 10:54
@kislyuk  so not good news unfortunately. 

I did find that actually the configuration for the standard library logging seems to have changed without my direct knowledge. 

I suspect that this may have been the reason that the issue simply "went away". 

I'm not able to recover the original configuration and neither am I able to commit time for code inspection here to try to determine what might have been the cause. 

All I can really tell you is that there was 100% an infinite loop and it reproduced in a deterministic way - it was always at the same log line that the loop was entered. I assume because at that point we had batched enough records to send. 

So in terms of ways forward for this - I really don't know. I would love to commit time here to try to figure out from code inspection what happened but of course as everyone else, I have many demands on my time. 

If anything does occur to me or I have any new information to share I can always reopen this issue should you choose to close it.

**Comment by kislyuk** [comment] 2021-05-15 00:03
I am going to close this issue at this point. It's entirely possible that the queue and shutdown protocol in watchtower can produce an infinite loop, however, without specific details on how to reproduce it, I can't fix it since in my usage watchtower does not trigger this condition.

**Closed by kislyuk** 2021-05-15 00:03 UTC
