### ISSUE TITLE
CloudWatch logs not showing up

### ISSUE THREAD

**Issue by JangoSteve** [kislyuk/watchtower#29] opened 2016-10-31 18:35 UTC
Hi there,

I don't know if this issue is specific to Watchtower, Python log handling in general, or AWS's cloudwatch CLI client/API, but I was hoping you may have an idea of what's going on.

I have watchtower set up and working with a couple different loggers, and usually my log messages show up in CloudWatch. However, I've noticed that it always seems like more of a sampling of log event messages rather than all of them. If I send 150k messages to a log, and then check the CloudWatch logs, there are only ~59k messages there. There are no errors logging any of the messages from the Python script.

I'm thinking it has something to do with the `send_interval`, `max_batch_size`, or `max_batch_count`, and the fact that the Python script just exits when it finishes. Is it possible that there are messages left on the local machine that are never getting sync'd to the CloudWatch API due to the Python script finishing and exiting before it hits the max interval, size, or count?

I also noticed there is a `flush` function in watchtower/__init__.py, should I be calling that internal function at the end of my Python script somehow? Here's the excerpt of my code that's sending logging information:

```py
# [clipped]

import watchtower, logging
import boto3

hostname = socket.gethostname()

session = boto3.Session(profile_name='my_cloudwatch_user')
error_logger = logging.getLogger('error_logger')
error_logger.setLevel(logging.ERROR)

def log_exception_hook(exc_type, exc_value, exc_traceback):
    error_logger.error(json.dumps({'type': 'global_error', 'error_type': str(exc_type.__name__), 'value': str(exc_value.message), 'traceback': ''.join(traceback.format_tb(exc_traceback)), 'hostname': hostname}))
    sys.__excepthook__(exc_type, exc_value, exc_traceback)
sys.excepthook = log_exception_hook

error_logger.addHandler(watchtower.CloudWatchLogHandler(log_group='my_log_group', boto3_session=session))

# Do some stuff here that sometimes causes errors

```

If this is an idiosyncrasy of Python logging or AWS's CloudWatch CLI, I apologize, but figured I'd ask here in case you knew of a way to handle this with Watchtower.

**Comment by kislyuk** [comment] 2016-10-31 22:38
The `flush()` method is part of logging's extensions API. Logging is supposed to automatically call flush when shutting down.

The maximum number of batched messages is 10K by default, so I'm not sure how to explain the fact that you received less than half of 150K messages. If the problem is reproducible, I would start by adding another handler (or not removing the default handler) so your logger prints to stderr, and comparing the number of messages printed locally vs. those in CWL.

**Comment by JangoSteve** [comment] 2016-11-01 03:06
Actually the process that had nearly 100k unlogged messages was running across 50 concurrent processes, so if it's possible for logging to not send logging events below the max-count threshold, it seems like that could be it? Or is the flush method from the extensions API supposed to address that?

**Comment by kislyuk** [comment] 2016-11-01 04:24
That's an interesting stress test. Yes, this is what could be happening: there is an average of ~5000 unsent messages accumulated per thread, and they all get lost because the shutdown procedure does not trigger `logging.shutdown()` for whatever reason. `logging.shutdown()` is supposed to fire automatically on interpreter exit: https://hg.python.org/cpython/file/2.7/Lib/logging/__init__.py#l1685.

If you have an application exit handler routine, could you try inserting `logging.shutdown()` there? Hopefully that will fix things. Perhaps the atexit handlers don't get fired properly in daemon threads. If that's the case, I'll have to find a general solution. I need to understand better how atexit handlers interact with threading.

**Comment by JangoSteve** [comment] 2016-11-01 14:07
@kislyuk awesome, that's a great help, thank you! I'll try the `logging.shutdown()` on the handlers. If it helps, most of our scripts run within a `while True` loop, watching for messages to process, and we just kill them with a `SIGINT` signal.

I haven't figured out if there are only specific processes that don't log all messages, or conversely some processes that always log _all_ messages, but from what I've seen, it seems like every process drops messages here and there. There are some processes that have something like this to do additional cleanup on exit:

```
def signal_term_handler(signal, frame):
    # do some additional cleanup here
    sys.exit(0)
signal.signal(signal.SIGTERM, signal_term_handler)
```

I'm somewhat new to Python (coming primarily from Ruby and JS), so I'm not sure about the intricacies of Python's logging or signal handling, so I don't know if the above simply adds functionality (as the name "handler" would imply), or if it overwrites the standard signal handling completely, such that you must manually include the operations that the standard signal handling would normally perform, such as `logging.shutdown()`. I would hope it's the former, but figured I'd mention it in case it's related.

And finally, some of our processes happen within machines that get terminated, and I'm not positive we always explicitly kill the process before terminating the machine. However, I've seen this behavior of not logging all messages even on my local machine when I am killing the Python process (and not shutting down my machine or closing the terminal), so while it could be also related, it doesn't seem to be the sole cause at least.

Anyway, figured I'd include all this info here in case it helps someone else that comes across this, but seems like it's (probably... maybe?) not specifically a Watchtower issue, but more possibly a Python logging issue, so I appreciate your feedback and direction.

I think what I'll try doing is calling `logging.shutdown()` in our exit handlers (and create one for our processes that don't have one), and make sure that our machine-terminating scripts always kill the processes first before destroying the machines, and see if that helps.

**Comment by mweitzel** [comment] 2016-11-16 00:02
Hello, I looked into this and I think the root of the issue is that `atexit` is not always called.

The [atexit docs](https://docs.python.org/2/library/atexit.html) state normal program termination should call the functions..

> At normal program termination (for instance, if sys.exit() is called or the main module’s execution completes), all functions registered are called in last in, first out order.

..but receiving a kill signal doesn't qualify

These are the default handlers for different kill signals:

```
>>> import signal
>>> for i in range(1,16):
...     print(i, signal.getsignal(i))
...
(1, 0)
(2, <built-in function default_int_handler>)
(3, 0)
(4, 0)
(5, 0)
(6, 0)
(7, 0)
(8, 0)
(9, None)
(10, 0)
(11, 0)
(12, 0)
(13, 1)
(14, 0)
(15, 0)
```

So [ctrl-c], (keyboard interrupt) will trigger a `sys.exit()`, but nothing else will until you set the handler yourself.

Signals with `0` use the default handler, which does nothing and ends python.
Signals with `1` ignoring the signal without even exiting
9 always exits without being handled

If a python process receives a kill signal for a signal with the default do-nothing handler, none of the `atexit` registered functions will ever be called, including the `logging`'s `shutdown`, which @kislyuk mentioned.

If you register a handler which does nothing but call `sys.exit()`, then all `atexit` registered functions are called, and the logs should flush.

**Comment by JangoSteve** [comment] 2016-11-16 21:12
@kislyuk, @mweitzel on our team figured out the above, so it looks like we have a way to solve the issue internally in our own usage, but I'm not sure if you'd want to add a default handler that calls `atexit` within Watchtower, or maybe we could just add a note about this caveat with an example to the docs.

**Comment by kislyuk** [comment] 2016-11-16 21:16
Thanks for the research. Yes, I need to update the docs to reflect this caveat. I doubt this should be the default behavior, but perhaps I can add a utility function that installs the signal handlers (which signals though?) and call it out in the docs.

PRs are also welcome for the above.

**Comment by mweitzel** [comment] 2016-11-16 21:44
@kislyuk np, and yes that's what we ended up doing, although very conservatively.

Where we initialize the logger we added something like:
```python
def _handler(signum, frame):
    print 'Signal handler called with signal', signum
    sys.exit(143) # standard response to sigterm

# Only set if blank, but do not override an existing handler!
if(signal.getsignal(15) in [0, 1, None]):
    signal.signal(15, _handler)
```

The second part could definitely be wrapped in a utility function, taking the signal of interest.

If that's the kind of thing you're looking for I can have a PR up sometime in the next week, with a  note in the docs as well.

**Comment by kislyuk** [comment] 2021-01-01 20:57
The correct way to shut down watchtower is, like with other Python logging handlers, by calling `logging.shutdown()` which will call `flush()` and `close()` on the watchtower log handler. In general, it is not acceptable for libraries to install their own signal handlers, and usually not advisable to install their own atexit functions either. Closing this issue; if there is new architectural feedback or suggestions, please open a new issue.

**Closed by kislyuk** 2021-01-01 20:57 UTC
