### ISSUE TITLE
WARNING - KeyError: 'nextSequenceToken

### ISSUE THREAD

**Issue by opensnippets** [kislyuk/watchtower#153] opened 2021-10-22 06:54 UTC
Hi,

I am a beginner of the cloudwatch and airflow, so please bear with me. I am maintaining an airflow and what I have seen in the log.
`[2021-10-01 08:00:11,345] {{logging_mixin.py:104}} WARNING -   File "/usr/local/lib/python3.7/site-packages/watchtower/__init__.py", line 185, in _submit_batch
    self.sequence_tokens[stream_name] = response["nextSequenceToken"]
[2021-10-01 08:00:11,368] {{logging_mixin.py:104}} WARNING - KeyError: 'nextSequenceToken'`
Currently, it is using watchtower==0.7.3 and boto3==1.17.53. 
If someone knows how to fix this WARNING, I would appreciate hearing from this issue thread.

Thanks.

**Comment by kislyuk** [comment] 2021-12-10 17:06
Hello, I am going to close this issue because I don't have a reproduction or any leads on it. If you think this is still a problem, feel free to reopen with specific details of how to reproduce it.

**Closed by kislyuk** 2021-12-10 17:06 UTC
