### ISSUE TITLE
InvalidSequenceTokenException in _submit_batch

### ISSUE THREAD

**Issue by aventurella** [kislyuk/watchtower#20] opened 2016-04-05 17:53 UTC
context:
- Running inside a docker container
- Running on AWS ECS
- Boto 1.3.0

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/watchtower/__init__.py", line 150, in batch_sender
    self._submit_batch(cur_batch, stream_name)
  File "build/bdist.linux-x86_64/egg/watchtower/__init__.py", line 91, in _submit_batch
    response = self.cwl_client.put_log_events(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore-1.4.8-py2.7.egg/botocore/client.py", line 228, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore-1.4.8-py2.7.egg/botocore/client.py", line 492, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidSequenceTokenException) when calling the PutLogEvents operation: The given sequenceToken is invalid. The next expected sequenceToken is: 49556659118894282282062119591701830007155923742915302338
```

I don't know if I should care about this error, or if it's just emitting and not actually harming the running application.

**Comment by jinty** [comment] 2016-04-06 13:44
duplicate of https://github.com/kislyuk/watchtower/issues/19

**Comment by kislyuk** [comment] 2016-04-06 15:24
Thank you for reporting. Left a comment in #19 with my thoughts on how to deal with this.

**Comment by kislyuk** [comment] 2021-01-01 20:52
Closing this now since InvalidSequenceTokenException handling has been implemented.

**Closed by kislyuk** 2021-01-01 20:52 UTC
