### ISSUE TITLE
Add timeout to flush() and close()

### ISSUE THREAD

**Issue by geertj** [kislyuk/watchtower#132] opened 2020-12-23 16:48 UTC
The python logging subsystem calls `flush()` and `close()` for each installed logger using an `atexit` handler.

In some cases, I noticed that a `CloudWatchLogHandler` can get stuck in either one of these, causing my scripts to not exit. It would be useful to have a timeout argument in the constructor that can limit the time spent waiting in `flush()` and `close()`.

**Comment by kislyuk** [comment] 2021-01-01 01:50
Can you elaborate on the circumstances in which the handler gets stuck? By design, the handler won't quit until it delivers all log messages to AWS, and will quit immediately thereafter. In the default configuration, watchtower aggregates log messages using a multithreaded queue to reduce the number of network requests made. This can cause a delay of up to 60 seconds before the messages get delivered, since there isn't a good way (that I know of) to let the handler thread know that the main thread is ready to quit. I prefer not to wrap this code in an arbitrary timeout without addressing the root cause.

**Comment by kislyuk** [comment] 2021-01-01 07:25
I am going to close this issue for now since it is highly unlikely that I will implement this feature as described. However, please do feel free to give your thoughts about the above, or open a PR if you have a proposed implementation in mind.

**Closed by kislyuk** 2021-01-01 07:25 UTC

**Comment by lyso** [comment] 2023-10-23 12:11
I am also experiencing stuck at flush or close when using v2.0.1. Here is the details:

The flush, for example, gets stuck at [this line](https://github.com/kislyuk/watchtower/blob/698ff2241befb6586269b6bbce0e305032c2d45c/watchtower/__init__.py#L482) `q.join()`, when there are `CreateLogStream` throttles and `use_queues==True`. Because all retries failed, the `_submit_batch()` give up clear up the queue, so the main thread got stuck.

Possible fix would be:
1. add time out in the flush and close, give up waiting after timeout.
2. never give up create log stream (this can only fix `CreateLogStream` related stuck)
3. Start a timer and a daemon thread when entering flush or close. When timer timeout, daemon thread drop all msg in the queue.

I can submit a PR, please let me know what would be the best way do you want to implement.
