### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mloo-sp** [kislyuk/watchtower#34] opened 2017-01-19 14:57 UTC
We have been noticing a memory leak with watchtower for long running processes.  
Logs are being delivered to Cloudwatch but memory usage keeps going up. 
Python version 2.7.10 and watchtower 0.3.3

Snippet of code to reproduce
```
import watchtower, logging, time

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(str(time.time()))
wt = watchtower.CloudWatchLogHandler(use_queues=True, send_interval=60, max_batch_count=10)
logger.addHandler(wt)
logger.propagate = False

for _ in xrange(50000):
    logger.info('Junk data | {}'.format("0" * 10000))
    time.sleep(0.05)
```

**Comment by kageurufu** [comment] 2017-03-28 22:59
I'm seeing this as well, and had to remove the watchtower handler to keep our servers alive

**Comment by jcerjak** [comment] 2018-02-08 12:30
I checked the snippet above with Python 2.7.6 and latest `watchtower` master by using the [memory_profiler](https://pypi.python.org/pypi/memory_profiler/0.51.0#time-based-memory-usage).

When using queues (`use_queues=True`):

![watchtower_memory_leak_with_queues](https://user-images.githubusercontent.com/191024/35971866-de9b077c-0ccf-11e8-9518-39769f6601d4.jpg)

Without using queues (`use_queues=False`):

![watchtower_memory_leak_no_queues](https://user-images.githubusercontent.com/191024/35971876-e8efd6e4-0ccf-11e8-864e-83d8ed2437b8.jpg)

Upon investigation, it seems that the issue is related to `botocore`, and might be further amplified with the way threads are used in `watchtower`: https://github.com/boto/botocore/issues/805

This seems to be confirmed by doing manual garbage collection after [pushing logs to CloudWatch](https://github.com/kislyuk/watchtower/blob/master/watchtower/__init__.py#L109):

```
import gc

...
response = self.cwl_client.put_log_events(**kwargs)
gc.collect()
```

When using queues `(use_queues=True)` and gc:

![watchtower_memory_leak_with_queues_and_gc](https://user-images.githubusercontent.com/191024/35972946-ec65fade-0cd3-11e8-9ad2-5e603ef3a38a.jpg)

**Comment by AbendGithub** [comment] 2021-08-03 08:04
According to this: https://github.com/boto/botocore/issues/1246#issuecomment-638369675

To avoid memory leaks using botocore/boto3, the idea is to create one session by thread. Currently this package creates a single session that is being used by every thread. This is causing this issue apparently.

**Comment by StevenMapes** [comment] 2022-02-11 12:23
Is this still an issue? I was about to use this package with for some clients but if it has memory leaks still like those shown above as their services tend to run a long time without restarting and that sort of memory burn rate will drain resources too quickly

**Comment by AbendGithub** [comment] 2022-02-11 16:11
I have not experienced problem related to this, but my service is small in comparison to others. According to this opened issue the problem with botocore still persists: https://github.com/boto/boto3/issues/1670

**Comment by kislyuk** [comment] 2022-02-11 22:55
We use watchtower in production and do not observe any memory leaks. Also, watchtower does not share boto3 clients across threads unless explicitly passed a configuration that forces it to do so.

I am going to close this issue for now. When I run the reproduction script above, it stabilizes at a steady state memory consumption of 60MB. Network outages and associated retries may temporarily increase this footprint. If somebody has a specific concern, please post a complete reproduction and an explanation of why it is different from what you expect.

**Closed by kislyuk** 2022-02-11 22:55 UTC
